### ISSUE TITLE
Error on data_actons#show page

### ISSUE THREAD

**Issue by jessieay** [18F/identity-deed#4]
steps to reproduce:
1. visit https://identity-deeds.18f.gov/admin/data_actions/1

this is the error I am seeing in the logs:

```
2016-10-26T10:22:50.18-0700 [App/0]      OUT Completed 500 Internal Server Error in 21ms (ActiveRecord: 1.7ms)
2016-10-26T10:22:50.18-0700 [App/0]      OUT ActionView::Template::Error (undefined method `list_row' for #<ActiveAdmin::Views::Pages::Show:0x007fb3003e62b8>):
2016-10-26T10:22:50.18-0700 [App/0]      OUT     1: insert_tag renderer_for(:show)
```

**Comment by typesend** [comment]
I see that `gem 'activeadmin_addons', '0.9.3'` was removed from the Gemfile. `#list_row` is a method provided by that gem.

**Comment by jessieay** [comment]
oh interesting! yeah I removed a bunch of random gems that I thought were unused. I guess this is where automated tests would have been helpful for knowing what I was breaking 😸

**Comment by typesend** [comment]
Just pushed the fix to Gemfile and Gemfile.lock

**Comment by jessieay** [comment]
cool @typesend -- could be good to do these as PRs in future. While there is flexibility in format of how code gets merged, getting peer signoff is a requirement of the 18F process ;)

**Comment by typesend** [comment]
@jessieay please redeploy so @JohnRahaghi can confirm the fix. Thank you!

**Comment by jessieay** [comment]
yup, he did confirm earlier on Slack! :)

**Comment by typesend** [comment]
Awesome just saw an email and wanted to make sure this could be closed
